Fix typo
ory/hydra pull request #2264
Opened 2020-12-21 21:10 UTC by bfrisbie-brex

2020-12-21 21:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ory/hydra?pullRequest=2264) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ory/hydra?pullRequest=2264) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ory/hydra?pullRequest=2264) it.</sub>

2020-12-25 10:34 UTC, aeneasr commented on docs/versioned_docs/version-v1.9/concepts/oauth2.mdx
> +- https://ory-hydra.example/oauth2/token?grant_type=client_credentials&...
@vinckr could you add this to the root docs in another pr as well please?

2020-12-25 10:35 UTC, aeneasr requested changes
Thank you for these changes! The documentation is a bit tricky at the moment as the change has to be made in two places, the file you edited and: https://github.com/ory/hydra/blob/05897d3e9f6ee1a2231eaa27b78f52ee7faf4d27/docs/docs/concepts/oauth2.mdx

2020-12-26 15:54 UTC, bfrisbie-brex commented
@aeneasr fixed in the 2nd spot too; thanks for pointing that out.

2020-12-31 07:52 UTC, merged

2020-12-31 07:52 UTC, aeneasr commented
Awesome 🎉 

Thank you for your contribution!