docs: improve readme tests section
ory/hydra pull request #2380
Opened 2021-03-04 18:28 UTC by Benehiko

## Related issue

## Proposed changes

Update the README.md file with the correct test commands as the previous ones were incomplete or out dated.

## Checklist

- [X] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [X] I have read the [security policy](../security/policy).
- [X] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added or changed [the documentation](docs/docs).

## Further comments

2021-03-05 10:53 UTC, zepatrik requested changes
Nice, the section was quite outdated it seems :sweat_smile:

2021-03-05 10:53 UTC, zepatrik commented on README.md
> +    make e2e
We usually use the fenced (backticks) codeblocks instead.

2021-03-05 10:53 UTC, zepatrik commented on README.md
> +thus add `-tags sqlite` when building the binary.
Even the full tests run against sqlite and require the tag.
```suggestion
All tests run against an sqlite in-memory database,
thus it is required to use the `-tags sqlite` build tag.
```

2021-03-05 10:53 UTC, zepatrik commented on README.md
> +cd client; go test -v -failfast -short -tags sqlite .
```suggestion
go test -v -failfast -short -tags sqlite ./client
```

2021-03-08 10:57 UTC, aeneasr approved these changes

2021-03-08 10:57 UTC, merged