Feature/async backchannel logout
ory/hydra pull request #2849
Opened 2021-11-10 10:24 UTC by aarmam

This pull request introduces feature to execute backchannel logout asynchronously.

Use case description:
User should not have to wait for backchannel requests to finish when performing logout from all applications using GET /oauth2/sessions/logout or from specific application by using DELETE /oauth2/auth/sessions/consent?trigger_backchannel_logout=true (https://github.com/ory/hydra/pull/2844)

## Related issue(s)

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [x] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added or changed [the documentation](docs/docs).

## Further Comments

**Tests and documentation will be commited after inital acceptance of the proposed feature.**

2021-11-24 13:42 UTC, aarmam commented on consent/strategy_default.go
>  		res, err := hc.PostForm(t.url, url.Values{"logout_token": {t.token}})
Retry could take 5 x 60sec request timeout + backoff time in between. We could generate updated logout token for each request so `iat` does not expire.
```golang
var body = retryablehttp.ReaderFunc(func() (io.Reader, error) {			
	return strings.NewReader(url.Values{"logout_token": {generateToken}}.Encode()), nil
})
req, err := retryablehttp.NewRequest("POST", c.BackChannelLogoutURI, body)
if err != nil {
	s.r.Logger().WithRequest(r).WithError(err).
		WithField("client_id", c.OutfacingID).
		WithField("backchannel_logout_url", c.BackChannelLogoutURI).
		Error("Unable to create OpenID Connect Back-Channel Logout Request")
	return
}
req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
res, err := hc.Do(req)
if err != nil {
	s.r.Logger().WithRequest(r).WithError(err).
		WithField("client_id", c.OutfacingID).
		WithField("backchannel_logout_url", c.BackChannelLogoutURI).
		Error("Unable to execute OpenID Connect Back-Channel Logout Request")
	return
}
```

2022-04-01 15:12 UTC, aeneasr requested changes
It looks like this PR is somewhat broken? There is only one file that has changes unrelated to the PR's title

2022-04-01 15:13 UTC, aeneasr requested changes
I think this makes sense! Could you please add some documentation that explains that this runs async?

2022-04-28 21:21 UTC, aeneasr approved these changes

2022-04-28 21:28 UTC, aeneasr approved these changes

2022-04-28 21:42 UTC, merged