Update login_consent_request value
ory/hydra pull request #2874
Opened 2021-11-27 02:52 UTC by ALTELMA

I've found the document mismatch with both between

https://www.ory.sh/hydra/docs/reference/configuration/

and

https://www.ory.sh/hydra/docs/guides/token-expiration/

Could you please review it?

## Related issue(s)

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [ ] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [ ] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added or changed [the documentation](docs/docs).

## Further Comments

2021-11-27 02:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ory/hydra?pullRequest=2874) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ory/hydra?pullRequest=2874) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ory/hydra?pullRequest=2874) it.</sub>

2021-11-28 10:49 UTC, aeneasr requested changes
Thank you for the PR! Unfortunately, this file is autogenerated so any changes to it will be overwritten the next time it is generated.

Also, I think the values are correct!

2021-11-28 10:49 UTC, aeneasr commented
Closing this, but feel free to open another PR with different fixes! :)

2021-11-28 10:49 UTC, closed without merging

2021-11-29 02:20 UTC, ALTELMA commented
> Thank you for the PR! Unfortunately, this file is autogenerated so any changes to it will be overwritten the next time it is generated.
> 
> Also, I think the values are correct!

@aeneasr What is the correct value? 30m or 1h? I am OK if you confirm this.