feat: basic auth support for hydra cli
ory/hydra pull request #3035
Opened 2022-03-15 11:20 UTC by phsym

Required for example in case where hydra admin endpoint
is protected behind a reverse proxy that enforces basic auth.
If `--access-token` arg is set, it takes precedence over basic auth

It does not apply to the `token revoke` command which goes though the public endpoint and already uses basic auth with clientId and clientSecret

## Related issue(s)

#2880 

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [ ] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [x] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added or changed [the documentation](docs/docs).

2022-03-15 11:21 UTC, phsym commented
Not sure how to proceed with the 3 remaining checkboxes for such a minor change

2022-03-20 12:04 UTC, aeneasr commented
Thank you! This look great :) Could you please add documentation to the commands (for example) explaining how to use this feature? Because right now it's very hidden in the code base and noone will really know how to use it!

2022-03-20 12:05 UTC, aeneasr requested changes
Thank you! This look great :) Could you please add documentation to the commands (for example) explaining how to use this feature? Because right now it's very hidden in the code base and noone will really know how to use it!

2022-03-25 10:19 UTC, aeneasr commented
While the PR is being worked on I will mark it as a draft. That declutters our review backlog :)

Once you're done with your changes and would like someone to review them, mark the PR as ready and request a review from one of the maintainers.

Thank you!

2022-03-30 16:47 UTC, phsym commented
> Thank you! This look great :) Could you please add documentation to the commands (for example) explaining how to use this feature? Because right now it's very hidden in the code base and noone will really know how to use it!

Hi, coming back on this (sorry, I was busy with other stuff). Sure, I'll add some doc to the command

2022-04-09 22:52 UTC, aeneasr commented
Is this ready for review? :)

2022-05-20 11:39 UTC, raman-nbg commented
@aeneasr what kind of documentation is required to complete this? Only in `cmd/clients.go` or also somewhere else?

Anyway, shouldn't the changes of `cmd/clients.go` should be added to other files (e.g. `cmd/keys.go`), too?

2022-05-20 12:17 UTC, phsym commented
Oh crap, this PR went totally out of my radar for some reason. @aeneasr I believe it's ready for review unless you see other parts that need to be documented

2024-05-23 06:26 UTC, closed without merging