feat: add `db.ignore_unknown_table_columns` configuration (#3192)
ory/hydra pull request #3193
Opened 2022-07-16 05:24 UTC by mih-kopylov

The property allows to ignore scan errors when columns in the SQL result have no fields in the destination struct.

## Related issue(s)

#3192 - it's described as a bug, and in order to fix the bug a configuration option is introduced, so that the existing behaviour is kept by default, while a new mode could be enabled.

I'm also happy for the new mode to be applied by default without a configuration flag, just let me know if it's the case.

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I have referenced an issue containing the design document if my change introduces a new feature.
- [x] I am following the [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security vulnerability. 
      If this pull request addresses a security vulnerability, 
      I confirm that I got green light (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added or changed [the documentation](https://github.com/ory/docs).

## Further Comments

2022-07-16 05:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ory/hydra?pullRequest=3193) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ory/hydra?pullRequest=3193) before we can accept your contribution.<br/><hr/>**Mikhail Kopylov** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ory/hydra?pullRequest=3193) it.</sub>

2022-07-16 05:36 UTC, mih-kopylov commented
I don't have any idea why some of the pipelines failed, especially one that validate JS or dockle.

It might be helpful to reflect the change in documentation, and an advise with a specific docs section to be updated is highly appreciated

2022-07-16 08:19 UTC, aeneasr requested changes
Thank you! :) Can you please add a test for provider.go to ensure that the setting works correctly? You will also need to add the config value to `spec/config.json` :)

Otherwise LGTM

2022-07-16 08:19 UTC, aeneasr commented on driver/registry_sql.go
> +			Unsafe:                    m.C.DbIgnoreUnknownTableColumns(),
Wow, I didn't know the solution is that easy! I thought it needed much more work. Great stuff! :)

2022-07-17 16:45 UTC, mih-kopylov commented
@aeneasr both done.
The only thing - it needs to have a real connection to a database for a proper test, so I used a postgres in docker and run the same query with both modes. Hope that's fine.

Can I kindly ask this patch to be a part of the next 1.11.x please?

2022-08-03 13:58 UTC, mih-kopylov commented
@aeneasr just a kind reminder

2022-08-25 07:41 UTC, aeneasr commented
Sorry, I dropped the ball on this one. The CI is currently failing, can you please take a look?

2022-08-25 12:17 UTC, aeneasr commented
@mih-kopylov the tests added in the PR seem to not be working: https://github.com/ory/hydra/runs/8015017590?check_suite_focus=true#step:12:40

2022-08-25 12:20 UTC, mih-kopylov commented
Thanks, I'll fix that once able to checkout `master` on Windows. Kinda chain of issues :)

2022-08-25 12:23 UTC, aeneasr commented
Ok, we'll get that one merged asap also

2022-08-25 12:30 UTC, aeneasr commented
i merged the fix to master

2022-10-04 09:31 UTC, aeneasr approved these changes
Awesome, thank you! 🎉 Your contribution makes Ory better :)

2022-10-04 09:31 UTC, merged