feat: Add config flag to allow specifying clientId on client creation
ory/hydra pull request #3354
Opened 2022-11-10 14:39 UTC by tinolazreg

Add a configuration flag to override the new change in Hydra v2.0, which made it no longer possible to choose the OAuth 2.0 Client ID. 
With this change, we will still enforce that the Client ID has to be a UUID, but it gives more flexibility to the users of Hydra.

## Related issue(s)
https://github.com/ory/hydra/issues/2911

## Checklist
- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [ ] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [ ] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got the approval (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added or changed [the documentation](https://github.com/ory/docs).

2022-11-10 14:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ory/hydra?pullRequest=3354) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ory/hydra?pullRequest=3354) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ory/hydra?pullRequest=3354) it.</sub>

2022-11-10 15:35 UTC, aeneasr requested changes
Unfortunately, as explained in [this comment](https://github.com/ory/hydra/issues/2911#issuecomment-1298440000), it's not possible to merge this PR. With this PR, we just push the inevitable (not being able to use your own IDs; ory changing to a new uuid format) down the line. I do understand that it is annoying that this is no longer possible, and Ory wants to be as helpful as we can in softening the impact of this change with pointed guides that hopefully help users adapt.

2022-11-11 12:30 UTC, tinolazreg commented
> Unfortunately, as explained in [this comment](https://github.com/ory/hydra/issues/2911#issuecomment-1298440000), it's not possible to merge this PR. With this PR, we just push the inevitable (not being able to use your own IDs; ory changing to a new uuid format) down the line. I do understand that it is annoying that this is no longer possible, and Ory wants to be as helpful as we can in softening the impact of this change with pointed guides that hopefully help users adapt.

Worth a try :) I thought maybe you could allow it, since it will be an opt-in flag that we would use at our own risk. But I get your point. I won't try to pursue this any further.

2022-11-21 13:58 UTC, aeneasr commented
Thank you for your understanding! Closing as discussed

2022-11-21 13:58 UTC, closed without merging