Refresh remember on use
ory/hydra pull request #3464
Opened 2023-03-11 11:49 UTC by sgal

## Related issue(s)
Picking up work done in https://github.com/ory/hydra/pull/2848 to speed up the delivery, since the author is on vacation.

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [ ] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [ ] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got the approval (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added or changed [the documentation](https://github.com/ory/docs).

## Further Comments

2023-03-13 10:36 UTC, aeneasr requested changes
Please add a migration test file for the new migration :)

2023-03-13 10:36 UTC, aeneasr commented on persistence/sql/migrations/20220914000001000000_support_refresh_remember_for.sqlite.up.sql
> +ALTER TABLE hydra_oauth2_flow ADD login_extend_session_lifespan BOOLEAN NOT NULL DEFAULT FALSE;
The migration timestamp should be later than the last migration which is:

```
20230228000010000001_client_add_skip_consent_column.up
```

Maybe just use the current date:

```
20230313112801000001_support_refresh_remember_for
```

2023-03-13 10:36 UTC, aeneasr commented on consent/types.go
> +	ExtendSessionLifespan bool `json:"extend_session_lifespan"`
```suggestion
	// Extend OAuth2 authentication session lifespan
	//
	// If set to `true`, the OAuth2 authentication cookie lifespan is extended. This is for example useful if you want the user to be able to use `prompt=none` continuously.
	//
	// This value can only be set to `true` if the user has an authentication, which is the case if the `skip` value is `true`.
	//
	// required: false
	ExtendSessionLifespan bool `json:"extend_session_lifespan"`
```

2023-03-15 08:11 UTC, sgal commented
@aeneasr Added migration test and fixed comments, please have a look!

2023-03-16 10:54 UTC, aeneasr approved these changes
Great job, thank you very much!

2023-03-16 10:56 UTC, merged