fix: don't query by raw signature
ory/hydra pull request #3593
Opened 2023-08-03 10:41 UTC by alnr

2023-08-03 11:36 UTC, hperl requested changes
You found all the right places, but the hasing only applies to access tokens (and the respective table), not all the other tables (refresh, id, code, pkce, oidc).

2023-08-03 11:36 UTC, hperl commented on persistence/sql/persister_oauth2.go
> -	signature = p.hashSignature(ctx, signature, table)
We still need this.

2023-08-03 11:36 UTC, hperl commented on persistence/sql/persister_oauth2.go
> -func (p *Persister) hashSignature(_ context.Context, signature string, table tableName) string {
We still need this function, because we only hash access token signatures.

2023-08-03 11:36 UTC, hperl commented on persistence/sql/persister_oauth2.go
> +			Where("signature = ?", SignatureHash(signature)).
```suggestion
			Where("signature = ?", signature).
```

2023-08-03 11:36 UTC, hperl commented on persistence/sql/persister_oauth2.go
> +				SignatureHash(signature),
No need to hash because authorization code signatures are not hashed.

2023-08-03 11:36 UTC, hperl commented on persistence/sql/persister_nid_test.go
> +			require.NoError(t, r.Persister().Connection(context.Background()).Find(&actual, persistencesql.SignatureHash(sig)))
Change not needed.

2023-08-03 11:36 UTC, hperl commented on persistence/sql/persister_nid_test.go
> +			require.NoError(t, r.Persister().Connection(context.Background()).Find(&actual, persistencesql.SignatureHash(sig)))
Change not needed.

2023-08-03 11:36 UTC, hperl commented on persistence/sql/persister_nid_test.go
> +			require.NoError(t, r.Persister().Connection(context.Background()).Find(&actual, persistencesql.SignatureHash(signature)))
Change not needed.

2023-08-03 11:36 UTC, hperl commented on persistence/sql/persister_nid_test.go
> +			require.NoError(t, r.Persister().Connection(context.Background()).Find(&actual, persistencesql.SignatureHash(signature)))
Change not needed.

2023-08-03 11:36 UTC, hperl commented on persistence/sql/persister_nid_test.go
> +			require.NoError(t, r.Persister().Connection(context.Background()).Find(&actual, persistencesql.SignatureHash(signature)))
Change not needed.

2023-08-03 11:36 UTC, hperl commented on persistence/sql/persister_nid_test.go
> +			require.NoError(t, r.Persister().Connection(context.Background()).Find(&actual, persistencesql.SignatureHash(signature)))
Change not needed.

2023-08-03 11:36 UTC, hperl commented on persistence/sql/persister_nid_test.go
> +			require.NoError(t, r.Persister().Connection(context.Background()).Find(&actual, persistencesql.SignatureHash(sig)))
Only these changes are needed in this file, the rest you can revert after you fix the code so that the hashing only happens for access tokens.

2023-08-03 13:24 UTC, aeneasr commented
Doesn't this break BC @hperl ?

2023-08-04 08:46 UTC, alnr commented on consent/handler.go
> -func (h *Handler) flowFromCookie(r *http.Request) (*flow.Flow, error) {
Unused

2023-08-04 09:02 UTC, hperl commented
> Doesn't this break BC @hperl ?

This should not not break backwards compatibility. We introduced undconditionally hashing all new access token signatures (before, we hashed only JWT access tokens). We kept the lookup for the raw signature in place so that old access tokens could still be found.

Since some time has passed, all current access tokens should have a hashed signature already, so removing the additional lookup for the raw signature can be removed safely.

2023-08-04 09:25 UTC, hperl approved these changes
LGTM!

2023-08-04 09:41 UTC, aeneasr commented
> Since some time has passed, all current access tokens should have a hashed signature already, so removing the additional lookup for the raw signature can be removed safely.

So it does have BC implications and those simply don't apply if you don't no longer have active tokens in the store. Scenarios where this isn't the case:

- Someone upgrading from hydra pre-hash to this version without running the interim version for a while. We have at least one customer I know that will run into this.
- Someone running (unreasonably high) TTLs for their access tokens 

Have we verified that there is indeed no active tokens in Ory Network any more that would be affected by this?

2023-08-08 07:55 UTC, hperl approved these changes
LGTM!

2023-08-08 09:10 UTC, aeneasr submitted a review, later dismissed

2023-08-08 10:49 UTC, hperl approved these changes

2023-08-08 14:09 UTC, merged